### ISSUE TITLE
Reproducibility issue with the obstacle avoidance

### ISSUE THREAD

**Issue by ParadoxRobotics** [cloudy/dmp-obstacle-avoidance#1]
Hi, 
I try to use a variation of your code for one my project, Unfortunately the PyrDMP library do not posses an "obstacle avoidance" parameter nor a functional implementation, but you use it here :
``
position_dmp = DMP(arg.gain, arg.num_gaussians, arg.stabilization, arg.obstacle_avoidance, arg.obstacle_gain)
``
Do you have a specific fork of the PyrDMP with a obstacle avoidance implementation ? because in the original implementation from Heracleia I can't found any trace : 
```
class DynamicMovementPrimitive:
    def __init__(self, _a, _ng, _stb):
```
Best regards, 

Quentin.

**Comment by cloudy** [comment]
Hi Quentin,

I don't this functionality was ever merged into the pyrdmp master though it exists in its own branch.

Please see here: https://github.com/heracleia/pyrdmp/tree/obstacle-avoidance

Thanks,
Joe

**Comment by ParadoxRobotics** [comment]
Thanks, for your reply !
I will probably create a C++ lib based on this code (for personal purpose only).

Best regards,
Quentin
